const GAMES=window.GALAXY_CATALOG.games;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentGame=null,currentCategory='all',currentQuery='';
function loadJSON(key,fallback){try{const raw=localStorage.getItem(key);if(raw)return JSON.parse(raw)}catch(e){}try{const x=JSON.parse(localStorage.getItem('youthGalaxy.records.v2')||'{}');for(const g of Object.values(x.games||{})){const raw=g?.legacy?.[key];if(raw!=null)return JSON.parse(raw)}}catch(e){}return fallback}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtTime(sec){if(sec==null||!isFinite(Number(sec)))return '—';sec=Math.max(0,Math.round(Number(sec)));return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function pushScore(rows,arr,meta=''){if(!Array.isArray(arr))return;arr.forEach(r=>rows.push({display:Number(r.score||0).toLocaleString('ru-RU'),meta:meta||[r.mode,r.difficulty].filter(Boolean).join(' • '),date:r.date||r.ts||0,sort:Number(r.score||0)}))}
function asRows(game){const id=game.id;let rows=[];
  if(id==='2048')pushScore(rows,loadJSON('youth2048Records',[]));
  else if(id==='backgammon'){pushScore(rows,loadJSON('youth_backgammon_short_records_v2',[]),'Короткие');pushScore(rows,loadJSON('youth_backgammon_long_records_v2',[]),'Длинные')}
  else if(id==='checkers')pushScore(rows,loadJSON('youthCheckersRecords',[]));
  else if(id==='chess')pushScore(rows,loadJSON('mm_games_chess_scores_v1',[]));
  else if(id==='connect4')pushScore(rows,loadJSON('youthConnect4Records',[]));
  else if(id==='corners')pushScore(rows,loadJSON('youthCornersRecords',[]));
  else if(id==='gomoku')pushScore(rows,loadJSON('youthGomokuRecords',[]));
  else if(id==='mahjong')pushScore(rows,loadJSON('youthMahjongV4Records',[]));
  else if(id==='reversi')pushScore(rows,loadJSON('youthReversiRecords',[]));
  else if(id==='starbattle')pushScore(rows,loadJSON('youthStarBattleRecords',[]));
  else if(id==='sudoku')pushScore(rows,loadJSON('youthSudokuRecords',[]));
  else if(id==='tictactoe')pushScore(rows,loadJSON('youthTttRecords',[]));
  else if(id==='fifteen'){const a=loadJSON('youthFifteenRecords',[]);if(Array.isArray(a))a.forEach(r=>rows.push({display:r.mode==='timed'?fmtTime(r.time):(r.moves+' ход.'),meta:(r.mode==='timed'?'На время':'Классика')+' • '+r.moves+' ход.',sort:-(r.mode==='timed'?Number(r.time||999999):Number(r.moves||999999)),date:r.date||0}))}
  else if(id==='memory'){const o=loadJSON('youthMemoryRecords',{});if(o&&typeof o==='object')Object.entries(o).forEach(([mode,r])=>{if(r&&typeof r==='object')rows.push({display:Number(r.score||0).toLocaleString('ru-RU'),meta:mode.replace('_',' • ')+' • '+fmtTime(r.time),sort:Number(r.score||0),date:r.ts||0})})}
  else if(id==='domino'){const o=loadJSON('youthDominoRecords',{});if(o&&typeof o==='object')Object.entries(o).forEach(([mode,r])=>{if(r&&typeof r==='object')rows.push({display:Number(r.best||0)+' очк.',meta:mode+' • '+Number(r.wins||0)+' побед',sort:Number(r.best||0),date:0})})}
  else if(id==='solitaire'){const o=loadJSON('youth_solitaire_records',{});if(o&&typeof o==='object')Object.entries(o).forEach(([mode,r])=>{if(r&&typeof r==='object')rows.push({display:Number(r.score||0).toLocaleString('ru-RU'),meta:(mode==='timed'?'На время':'Классика')+' • '+fmtTime(r.bestTime),sort:Number(r.score||0),date:0})})}
  else if(game.recordsFormat==='retro-score'){
    const g=window.YouthRecords?.getGame?.(id),names={a:'GAME A',b:'GAME B',turbo:'TURBO'};
    // One best per mode: these are independent score scales, never one mixed ranking.
    for(const mode of ['a','b','turbo']){const list=g?.records?.[mode];if(!Array.isArray(list))continue;const r=list.filter(r=>r&&typeof r.score==='number'&&Number.isFinite(r.score)&&r.score>=0).sort((a,b)=>b.score-a.score)[0];if(r)rows.push({display:r.score.toLocaleString('ru-RU'),meta:names[mode]+' • '+Number(r.caught??r.delivered??0)+' '+game.recordUnit,sort:r.score,date:r.date||0})}
    return rows;
  }
  rows.sort((a,b)=>(b.sort||0)-(a.sort||0)||(Number(b.date)||0)-(Number(a.date)||0));return rows
}
function bestLabel(game){const rows=asRows(game);if(game.recordsFormat==='retro-score')return rows.length?rows.map(r=>r.meta.split(' • ')[0]+': '+r.display).join(' • '):'Рекордов пока нет';if(game.id==='2048'){const best=Math.max(window.YouthRecords?.getBest('4x4','2048')||0,window.YouthRecords?.getBest('5x5','2048')||0,Number(rows[0]?.sort||0));if(best)return 'Лучшее: '+best.toLocaleString('ru-RU')}if(!rows.length)return 'Рекордов пока нет';return 'Лучшее: '+rows[0].display}
function renderGames(){const grid=$('#gameGrid');grid.innerHTML='';const q=currentQuery.trim().toLowerCase();GAMES.filter(g=>(currentCategory==='all'||g.cat===currentCategory)&&(!q||g.title.toLowerCase().includes(q)||g.full.toLowerCase().includes(q)||g.desc.toLowerCase().includes(q))).forEach((g,i)=>{const el=document.createElement('article');el.className='card gameLaunch';el.dataset.play=g.id;el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label','Открыть игру '+g.title);el.dataset.color=g.color;const pos=`${12+(i*17)%76}% ${15+(i*23)%70}%`;el.innerHTML=`<div class="cardVisual" style="--pos:${pos}">${g.assets.iconActive?`<img class="gameIconPose" src="${g.assets.iconActive}" alt="" aria-hidden="true">`:""}<img class="gameIconImg" src="${g.assets.icon}" alt="${esc(g.title)}"></div><div class="cardBody"><h3 class="u"><span class="sr-only">${esc(g.title)}</span><img class="catalogTitleArt" src="${g.assets.title}" alt="" aria-hidden="true"></h3><p>${esc(g.desc)}</p><div class="cardFoot"><div class="best" id="best-${g.id}">${esc(bestLabel(g))}</div></div></div>`;const pose=el.querySelector(".gameIconPose");if(pose){const ready=()=>el.classList.add("poseReady");if(pose.complete&&pose.naturalWidth)ready();else pose.addEventListener("load",ready,{once:true});}grid.appendChild(el)});if(!grid.children.length)grid.innerHTML='<div class="empty">Ничего не найдено. Попробуйте другой запрос.</div>'}
function updateBestLabels(){GAMES.forEach(g=>{const el=$('#best-'+g.id);if(el)el.textContent=bestLabel(g)});if($('#recordsPanel').classList.contains('active'))renderRecords()}
function showPanel(name){$$('.panel').forEach(p=>p.classList.toggle('active',p.id===name+'Panel'));$$('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));if(name==='records')renderRecords();window.scrollTo({top:0,behavior:'smooth'})}
let loadTimer=null,previewTimer=null,loadEpoch=0,loadPhase='idle';
function finishLaunchPreview(){clearTimeout(previewTimer);previewTimer=null;launchPending=false;$$('.poseLaunching').forEach(card=>{card.classList.remove('poseLaunching');card.removeAttribute('aria-busy')})}
function gameError(message){if(!currentGame)return;finishLaunchPreview();loadPhase='error';clearTimeout(loadTimer);const box=$('#gameLoading');box.replaceChildren();box.classList.add('error');box.style.display='flex';$('#gameModal').classList.add('open');$('#gameModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';const text=document.createElement('div');text.textContent='Не удалось запустить игру: '+message;const retry=document.createElement('button');retry.textContent='Повторить';retry.onclick=()=>openGame(currentGame.id);const back=document.createElement('button');back.textContent='Вернуться в каталог';back.onclick=closeGame;box.append(text,retry,back)}
function gameReady(){if(loadPhase!=='loading')return;finishLaunchPreview();loadPhase='ready';clearTimeout(loadTimer);$('#gameLoading').style.display='none';$('#gameModal').classList.add('open');$('#gameModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function openGame(id){const g=GAMES.find(x=>x.id===id);if(!g)return;clearTimeout(loadTimer);const epoch=++loadEpoch;currentGame=g;loadPhase='loading';$('#gameTitle').textContent=g.title;const frame=$('#gameFrame'),box=$('#gameLoading');box.classList.remove('error');box.textContent='🚀 Загрузка игры…';box.style.display='block';$('#gameModal').classList.remove('open');$('#gameModal').setAttribute('aria-hidden','true');document.body.style.overflow='';$('#gameModal').dataset.screen='splash';frame.src=g.entry+'?launch='+epoch;loadTimer=setTimeout(()=>{if(epoch===loadEpoch&&loadPhase==='loading')gameError('Игра не подтвердила готовность за 15 секунд. Проверьте соединение и повторите запуск.')},15000)}
function closeGame(){finishLaunchPreview();clearTimeout(loadTimer);++loadEpoch;loadPhase='idle';const frame=$('#gameFrame');frame.src='about:blank';$('#gameModal').classList.remove('open');$('#gameModal').setAttribute('aria-hidden','true');$('#gameLoading').style.display='none';document.body.style.overflow='';currentGame=null;showPanel('games');updateBestLabels()}
function fullscreenGame(){const box=$('#gameModal');if(!document.fullscreenElement)box.requestFullscreen?.();else document.exitFullscreen?.()}
function renderRecords(){const wrap=$('#recordGrid');wrap.innerHTML='';let gamesWith=0,total=0;const withRecords=[];GAMES.forEach(g=>{const all=asRows(g);if(all.length){gamesWith++;total+=all.length;withRecords.push({g,rows:all.slice(0,5)})}});$('#gamesWithRecords').textContent=gamesWith;$('#totalRecords').textContent=total;if(!withRecords.length){wrap.innerHTML='<section class="recordsEmpty"><div class="recordsEmptyIcon">🏆</div><h3 class="u">Здесь появятся ваши достижения</h3><p>Сыграйте первую партию. Как только игра сохранит результат, он автоматически появится в этом разделе.</p><button class="playBtn" onclick="showPanel(\'games\')">Выбрать игру</button></section>';return}withRecords.forEach(({g,rows})=>{const card=document.createElement('section');card.className='recordGame';card.innerHTML=`<div class="recordGameHead"><img class="miniImg" src="${g.assets.icon}" alt=""><b><span class="sr-only">${esc(g.title)}</span><img class="recordTitleArt" src="${g.assets.title}" alt="" aria-hidden="true"></b></div><div class="rows"></div>`;const box=card.querySelector('.rows');rows.forEach((r,i)=>{const row=document.createElement('div');row.className='row';row.innerHTML=`<div class="rank">${i+1}</div><div><div class="rname">Результат ${i+1}</div><span class="rmeta">${esc(r.meta||'Личный результат')}</span></div><div class="rvalue">${esc(r.display)}</div>`;box.appendChild(row)});wrap.appendChild(card)})}
function showInfo(type){const data=type==='how'?{icon:'🎮',title:'Как пользоваться платформой',html:'<p><b>1.</b> Выберите категорию или найдите игру через поиск.</p><p><b>2.</b> Нажмите на карточку игры. Она откроется прямо внутри платформы.</p><p><b>3.</b> Все игры адаптированы под вертикальный экран телефона. Кнопка ⌂ внутри игры возвращает в каталог.</p><p><b>4.</b> После партии откройте «Мои рекорды». Результаты сохраняются в браузере этого устройства.</p>'}:{icon:'🚀',title:'О проекте',html:'<p><b>«Игровая галактика»</b> объединяет 18 браузерных игр в одном космо-неоновом мире.</p><p>Регистрация сейчас не требуется. Платформа не создаёт профиль и не показывает аватар.</p><p><b>Рекорды:</b> текущая версия хранит личные результаты локально. Позже можно подключить общий онлайн-рейтинг через серверную базу без обязательной регистрации.</p>'};$('#infoIcon').textContent=data.icon;$('#infoTitle').textContent=data.title;$('#infoContent').innerHTML=data.html;$('#infoModal').classList.add('open');$('#infoModal').setAttribute('aria-hidden','false')}
function closeInfo(){$('#infoModal').classList.remove('open');$('#infoModal').setAttribute('aria-hidden','true')}
let launchPending=false;
function launchCard(card){if(launchPending)return;launchPending=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;card.classList.add('poseLaunching');card.setAttribute('aria-busy','true');previewTimer=setTimeout(()=>{previewTimer=null;if(launchPending)openGame(card.dataset.play)},reduced?0:150)}
// A touch release launches immediately after a tap, without waiting for hover-emulated click.
// A moved/cancelled pointer belongs to scrolling and never launches a card.
let cardTouch=null;
$('#gameGrid').addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||!e.isPrimary)return;const card=e.target.closest('.gameLaunch[data-play]');if(card)cardTouch={id:e.pointerId,card,x:e.clientX,y:e.clientY,moved:false}},{passive:true});
$('#gameGrid').addEventListener('pointermove',e=>{if(cardTouch?.id===e.pointerId&&Math.hypot(e.clientX-cardTouch.x,e.clientY-cardTouch.y)>10)cardTouch.moved=true},{passive:true});
$('#gameGrid').addEventListener('pointercancel',()=>{cardTouch=null},{passive:true});
$('#gameGrid').addEventListener('pointerup',e=>{const tap=cardTouch;cardTouch=null;if(tap?.id===e.pointerId&&!tap.moved&&Math.hypot(e.clientX-tap.x,e.clientY-tap.y)<=10&&e.target.closest('.gameLaunch[data-play]')===tap.card)launchCard(tap.card)},{passive:true});
$('#gameGrid').addEventListener('click',e=>{const card=e.target.closest('.gameLaunch[data-play]');if(card)launchCard(card)});
$('#gameGrid').addEventListener('keydown',e=>{const card=e.target.closest('.gameLaunch[data-play]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();if(!e.repeat)launchCard(card)}});
let centerFrame=0;
function updateCenter(){centerFrame=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;for(const card of document.querySelectorAll('.gameLaunch')){const rect=card.getBoundingClientRect();const closeness=Math.max(0,1-Math.abs(rect.top+rect.height/2-innerHeight/2)/(innerHeight*.42));card.style.setProperty('--center-scale',reduced?'1':String(1+closeness*.35))}}
function scheduleCenter(){if(!centerFrame)centerFrame=requestAnimationFrame(updateCenter)}
window.addEventListener('scroll',scheduleCenter,{passive:true});window.addEventListener('resize',scheduleCenter,{passive:true});new MutationObserver(scheduleCenter).observe($('#gameGrid'),{childList:true});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',scheduleCenter);scheduleCenter();

$('#search').addEventListener('input',e=>{currentQuery=e.target.value;renderGames()});$('#searchFocus').addEventListener('click',()=>$('#search').focus());
$('#categoryBar').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;currentCategory=b.dataset.cat;$$('.catBtn').forEach(x=>x.classList.toggle('active',x===b));renderGames()});
$$('[data-panel]').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.panel)));$$('.infoBtn').forEach(b=>b.addEventListener('click',()=>showInfo(b.dataset.info)));
$('#closeGame').addEventListener('click',closeGame);$('#fullGame').addEventListener('click',fullscreenGame);$('#gameFrame').addEventListener('load',()=>{if(!currentGame||loadPhase!=='loading')return;try{const frame=$('#gameFrame');const doc=frame.contentDocument;if(!doc?.querySelector('#splash')){gameError('Файл игры отсутствует или сервер вернул другую страницу.');return}frame.contentWindow.postMessage({type:'mm-game-probe'},location.origin)}catch(e){gameError('Нет доступа к странице игры.')}});$('#gameFrame').addEventListener('error',()=>gameError('Ошибка загрузки страницы игры.'));

$('#infoClose').addEventListener('click',closeInfo);$('#infoModal').addEventListener('click',e=>{if(e.target.id==='infoModal')closeInfo()});
window.addEventListener('message',e=>{if(!e.data||e.origin!==location.origin)return;const frame=$('#gameFrame');const fromGame=frame&&e.source===frame.contentWindow;if(e.data.type==='mm-game-screen'&&fromGame&&e.data.game===currentGame?.id&&e.data.launch===loadEpoch)$('#gameModal').dataset.screen=e.data.screen;if(e.data.type==='mm-records-changed'&&fromGame)setTimeout(updateBestLabels,100);if(e.data.type==='mm-game-ready'&&fromGame&&e.data.game===currentGame?.id&&e.data.launch===loadEpoch)gameReady();if(e.data.type==='mm-game-error'&&fromGame&&e.data.game===currentGame?.id&&e.data.launch===loadEpoch)gameError(e.data.message);if(e.data.type==='mm-exit-to-platform'&&fromGame)closeGame();});window.addEventListener('storage',updateBestLabels);window.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#gameModal').classList.contains('open')||loadPhase==='loading'||launchPending)closeGame();else closeInfo()}});
renderGames();updateBestLabels();showPanel(location.hash==='#records'?'records':'games');
