(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],ID='space-mail';
const MODE={a:{label:'GAME A · Смена',spawn:[2200,1700],deadline:[9500,7500],capacity:4,target:15,mul:1},b:{label:'GAME B · Поток',spawn:[1800,950],deadline:[8500,4800],capacity:5,target:null,mul:1},turbo:{label:'TURBO · Экспресс',spawn:[1300,650],deadline:[6200,3500],capacity:5,target:null,mul:2}};
const DEST=[{name:'Звезда',glyph:'★'},{name:'Луна',glyph:'☾'},{name:'Орбита',glyph:'◉'}],HERO={corgi:{name:'Капитан Корги',src:'../../assets/corgi.png'},cat:{name:'Космо-Кот',src:'../../assets/cat.png'}};
let phase='splash',hero='corgi',mode='a',recordMode='a',score=0,lives=3,delivered=0,errors=0,streak=0,bestStreak=0,route=null,queue=[],clock=0,spawnElapsed=0,seq=0,raf=0,lastTs=null,saved=false,soundOn=true,audio=null,lastBar=-1;const voices=new Set();
const cfg=()=>MODE[mode],finite=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
function data(){return window.YouthRecords?.getGame?.(ID)||{}}
function best(){const n=window.YouthRecords?.getBest?.(mode,ID);return finite(n)?n:0}
function params(){const t=Math.min(1,delivered/45),c=cfg();return {spawn:c.spawn[0]+(c.spawn[1]-c.spawn[0])*t,deadline:c.deadline[0]+(c.deadline[1]-c.deadline[0])*t}}
function stopAudio(){for(const o of voices){try{o.stop()}catch{}}voices.clear();if(audio?.state==='running')audio.suspend().catch(()=>{})}
function stop(){cancelAnimationFrame(raf);raf=0;lastTs=null;GameLifecycle.begin();stopAudio();for(const a of $('#mailField').getAnimations({subtree:true}))a.cancel()}
function show(id){stop();phase=id;$$('.screen').forEach(e=>e.classList.toggle('active',e.id===id));$$('.overlay').forEach(e=>e.classList.remove('open'));document.body.classList.remove('paused')}
function setHero(id){hero=HERO[id]?id:'corgi';$$('[data-hero]').forEach(b=>{const on=b.dataset.hero===hero;b.classList.toggle('on',on);b.setAttribute('aria-pressed',String(on))});$('#playerImg').src=HERO[hero].src;$('#playerImg').alt=HERO[hero].name}
function hud(){const values={scoreValue:score.toLocaleString('ru-RU'),bestValue:Math.max(best(),score).toLocaleString('ru-RU'),livesValue:'●'.repeat(lives)+'○'.repeat(3-lives),deliveredValue:cfg().target?`${delivered} / ${cfg().target}`:delivered,speedText:'Скорость '+Math.min(9,1+Math.floor(delivered/6)),queueText:`Очередь ${queue.length} / ${cfg().capacity}`,goalText:cfg().target?'Смена: 15 доставок':'Доставляйте до трёх ошибок'};for(const [id,value] of Object.entries(values))$('#'+id).textContent=value;$('#livesValue').setAttribute('aria-label','Жизней: '+lives)}
function render(){const item=queue[0];$('#currentParcel').classList.toggle('empty',!item);$('#parcelGlyph').textContent=item?DEST[item.dest].glyph:'✉';$('#parcelName').textContent=item?DEST[item.dest].name:'Ожидание';$('#currentParcel').dataset.dest=item?item.dest:'';const q=$('#queue');q.replaceChildren();for(let i=0;i<cfg().capacity;i++){const el=document.createElement('div'),p=queue[i];el.className=p?'queueParcel':'queueSlot';if(p){el.textContent=DEST[p.dest].glyph;const label=document.createElement('small');label.textContent=i===0?'Сейчас':String(i+1);el.append(label);el.setAttribute('aria-label',`${i+1}: ${DEST[p.dest].name}`)}q.append(el)}
 $$('.routeBtn[data-route]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.route)===route)));$$('[data-station]').forEach(e=>e.classList.toggle('selected',Number(e.dataset.station)===route));$('#routingBeam').dataset.route=route===null?'':route;$('#dispatchBtn').disabled=phase!=='playing'||!item||route===null;$('#dispatchBtn').textContent=route===null?'Выберите адрес · отправить ↗':'Отправить → '+DEST[route].name;lastBar=-1;bar();hud()}
function bar(){const p=queue[0],percent=p?Math.max(0,Math.ceil(100*(p.expires-clock)/p.ttl)):0;if(percent===lastBar)return;lastBar=percent;$('#deadlineBar').style.transform=`scaleX(${percent/100})`;$('#deadlineBar').setAttribute('aria-valuenow',percent);$('.deadline').classList.toggle('urgent',!!p&&percent<25)}
function choose(n){if(phase!=='playing'||!Number.isInteger(n)||n<0||n>=DEST.length)return;route=n;render();tone('move')}
function mistake(text){if(phase!=='playing')return;lives--;errors++;streak=0;$('#stateText').textContent=text;tone('miss');if(lives===0)finish(false)}
function dispatch(){if(phase!=='playing'||route===null||!queue.length)return;const item=queue.shift(),selected=route;route=null;if(selected===item.dest){delivered++;streak++;bestStreak=Math.max(streak,bestStreak);const gain=10*cfg().mul*Math.min(3,1+Math.floor((streak-1)/5));score+=gain;$('#stateText').textContent='Доставлено: '+DEST[item.dest].name+' +'+gain;tone('catch');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)$(`[data-station="${item.dest}"]`).animate([{filter:'brightness(1)'},{filter:'brightness(1.65)'},{filter:'brightness(1)'}],{duration:240});if(cfg().target&&delivered>=cfg().target){finish(true);return}}else mistake('Неверный адрес: нужна '+DEST[item.dest].name.toLowerCase());render()}
function spawn(){if(queue.length>=cfg().capacity){mistake('Очередь переполнена! Отправляйте быстрее.');return}const ttl=params().deadline;queue.push({id:++seq,dest:Math.floor(Math.random()*3),ttl,expires:clock+ttl});render()}
function tick(ts){raf=0;if(phase!=='playing')return;const dt=lastTs===null?0:Math.max(0,Math.min(50,ts-lastTs));lastTs=ts;clock+=dt;spawnElapsed+=dt;const expired=queue.filter(p=>p.expires<=clock);if(expired.length){queue=queue.filter(p=>p.expires>clock);route=null;for(const p of expired){mistake('Срок истёк: '+DEST[p.dest].name);if(phase!=='playing')return}render()}if(spawnElapsed>=params().spawn){spawnElapsed=0;spawn();if(phase!=='playing')return}bar();raf=requestAnimationFrame(tick)}
function start(m=mode){show('game');mode=MODE[m]?m:'a';phase='playing';score=0;lives=3;delivered=0;errors=0;streak=0;bestStreak=0;queue=[];clock=0;spawnElapsed=0;route=null;saved=false;$('#modeBadge').textContent=cfg().label;$('#pauseBtn').textContent='Ⅱ';$('#pauseBtn').setAttribute('aria-label','Пауза');$('#stateText').textContent='Выберите адрес, затем отправьте';setHero(hero);spawn();render();raf=requestAnimationFrame(tick)}
function pause(force){if(!['playing','paused'].includes(phase))return;const on=typeof force==='boolean'?force:phase==='playing';cancelAnimationFrame(raf);raf=0;lastTs=null;phase=on?'paused':'playing';document.body.classList.toggle('paused',on);$('#pauseBtn').textContent=on?'▶':'Ⅱ';$('#pauseBtn').setAttribute('aria-label',on?'Продолжить':'Пауза');$('#stateText').textContent=on?'Пауза • нажмите ▶':'Выберите адрес, затем отправьте';$('#dispatchBtn').disabled=on||route===null||!queue.length;if(on)stopAudio();else raf=requestAnimationFrame(tick)}
function save(won){if(saved)return;saved=true;const d=data(),records=d.records&&typeof d.records==='object'?{...d.records}:{},old=Array.isArray(records[mode])?records[mode].filter(r=>r&&finite(r.score)):[];const row={score,delivered,errors,bestStreak,won,mode,date:new Date().toISOString()};records[mode]=[...old,row].sort((a,b)=>b.score-a.score).slice(0,10);window.YouthRecords?.saveGame?.({records,last:row},ID);window.YouthRecords?.updateBest?.(mode,score,ID);if(parent!==window)parent.postMessage({type:'mm-records-changed',game:ID},location.origin)}
function finish(won){if(phase!=='playing')return;phase='result';stop();save(won);$('#resultTitle').textContent=won?'Смена выполнена!':'Смена завершена';$('#resultText').textContent=won?'Все 15 посылок доставлены. Отличная работа!':`Доставлено ${delivered} посылок. Ошибки, истёкшие сроки и переполнение очереди отнимают жизни.`;$('#resultScore').textContent=score.toLocaleString('ru-RU');$('#resultDelivered').textContent=delivered;$('#resultErrors').textContent=errors;$('#dispatchBtn').disabled=true;hud();$('#resultOverlay').classList.add('open');tone(won?'win':'miss')}
function records(){const box=$('#recordsList');box.replaceChildren();$$('[data-record-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.recordMode===recordMode)));const arr=data().records?.[recordMode],rows=Array.isArray(arr)?arr.filter(r=>r&&finite(r.score)).slice(0,10):[];if(!rows.length){const p=document.createElement('p');p.textContent='Пока нет результатов в '+MODE[recordMode].label;box.append(p)}rows.forEach((r,i)=>{const row=document.createElement('div');row.className='record';for(const text of [i+1,`${Number(r.delivered)||0} доставок${r.won?' · Смена выполнена':''}`,r.score.toLocaleString('ru-RU')]){const e=document.createElement('span');e.textContent=text;row.append(e)}box.append(row)})}
function tone(kind){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const t=audio.currentTime,g=audio.createGain();g.connect(audio.destination);g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+.3);const fs={move:[350],catch:[600,850],miss:[170,130],win:[550,740,950]}[kind];fs.forEach((f,i)=>{const o=audio.createOscillator();voices.add(o);o.frequency.value=f;o.connect(g);o.onended=()=>{voices.delete(o);o.disconnect()};o.start(t+i*.065);o.stop(t+i*.065+.08)});GameLifecycle.schedule(()=>g.disconnect(),500)}catch{}}
$('#startBtn').onclick=()=>show('menu');$$('[data-hero]').forEach(b=>b.onclick=()=>setHero(b.dataset.hero));$$('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$$('.routeBtn[data-route]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.route)));$('#dispatchBtn').onclick=dispatch;$('#pauseBtn').onclick=()=>pause();$('#homeBtn').onclick=()=>show('menu');$('#newBtn').onclick=()=>start();$('#resultMenu').onclick=()=>show('menu');$('#resultReplay').onclick=()=>start();$('#recordsBtn').onclick=()=>{records();$('#recordsOverlay').classList.add('open')};$('#recordsClose').onclick=()=>$('#recordsOverlay').classList.remove('open');$$('[data-record-mode]').forEach(b=>b.onclick=()=>{recordMode=b.dataset.recordMode;records()});$('#screenBtn').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else document.documentElement.requestFullscreen?.().catch(()=>{})};$('#soundBtn').onclick=()=>{soundOn=!soundOn;if(!soundOn)stopAudio();$('#soundBtn').textContent=soundOn?'♪':'×';$('#soundBtn').setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук')};
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||$$('.overlay.open').length){if(e.code==='Escape'&&$('#recordsOverlay').classList.contains('open'))$('#recordsOverlay').classList.remove('open');return}if(!['playing','paused'].includes(phase))return;const n={Digit1:0,Digit2:1,Digit3:2,Numpad1:0,Numpad2:1,Numpad3:2}[e.code];if(n!==undefined){e.preventDefault();choose(n)}if(e.code==='Enter'){e.preventDefault();if(!e.repeat)dispatch()}if(e.code==='Space'){e.preventDefault();if(!e.repeat)pause()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&phase==='playing')pause(true)});window.addEventListener('resize',()=>{if(phase==='playing'&&innerWidth>innerHeight&&innerHeight<500){pause(true);$('#stateText').textContent='Поворот экрана • нажмите ▶'}});window.addEventListener('pagehide',()=>{stop();phase='closed';audio?.close().catch(()=>{})});setHero('corgi');show('splash');window.__SPACE_MAIL_QA__={snapshot:()=>({phase,hero,mode,score,lives,delivered,errors,route,clock,framePending:raf!==0,capacity:cfg().capacity,params:params(),soundOn,audioState:audio?.state||'none',activeVoices:voices.size,queue:queue.map(p=>({id:p.id,dest:p.dest,remaining:p.expires-clock}))})};GameLifecycle.requiredImages=Object.values(HERO).map(h=>h.src);GameLifecycle.engineInitialized=true;
})();
