(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],ID='radio-beacon';
const MODES={a:{label:'GAME A · Поиск',drift:0,seconds:4,drain:1,mul:1},b:{label:'GAME B · Дрейф',drift:.8,seconds:5,drain:1.1,mul:1.5},turbo:{label:'TURBO · Помехи',drift:1.1,seconds:4.5,drain:1.2,mul:2}};
const HERO={corgi:{name:'Капитан Корги',src:'../../assets/corgi.png'},cat:{name:'Космо-Кот',src:'../../assets/cat.png'}};
const finite=n=>typeof n==='number'&&Number.isFinite(n)&&n>=0;
let phase='splash',hero='corgi',mode='a',recordMode='a',frequency=50,target=50,direction=1,step=1,energy=100,score=0,messages=0,progress=0,clock=0,locked=false,saved=false,raf=0,lastTs=null,soundOn=true,audio=null,signal=0,noise='clear',lastRender='';const voices=new Set();
const cfg=()=>MODES[mode],data=()=>window.YouthRecords?.getGame?.(ID)||{},best=()=>{const n=window.YouthRecords?.getBest?.(mode,ID);return finite(n)?n:0};
function stopAudio(){for(const o of voices){try{o.stop()}catch{}}voices.clear();if(audio?.state==='running')audio.suspend().catch(()=>{})}
function stop(){cancelAnimationFrame(raf);raf=0;lastTs=null;GameLifecycle.begin();stopAudio()}
function show(id){stop();phase=id;$$('.screen').forEach(e=>e.classList.toggle('active',e.id===id));$$('.overlay').forEach(e=>e.classList.remove('open'));document.body.classList.remove('paused')}
function setHero(id){hero=HERO[id]?id:'corgi';$$('[data-hero]').forEach(b=>{const on=b.dataset.hero===hero;b.classList.toggle('on',on);b.setAttribute('aria-pressed',String(on))});$('#playerImg').src=HERO[hero].src;$('#playerImg').alt=HERO[hero].name}
function interference(){if(mode!=='turbo')return {kind:'clear',wait:0};const t=clock%16500;return t>=15000?{kind:'active',wait:(16500-t)/1000}:t>=12000?{kind:'warning',wait:(15000-t)/1000}:{kind:'clear',wait:(12000-t)/1000}}
function readSignal(){return Math.max(0,Math.round(100-Math.abs(target-frequency)*7))}
function render(force=false){signal=readSignal();const interferenceState=interference();noise=interferenceState.kind;const transfer=Math.max(0,Math.floor(progress*100/cfg().seconds));const signature=[frequency,signal,transfer,Math.ceil(energy),score,messages,locked,step,phase,noise,Math.ceil(interferenceState.wait)].join('|');if(!force&&signature===lastRender)return;lastRender=signature;
const values={frequencyValue:frequency,signalValue:signal+'%',transferValue:transfer+'%',energyValue:Math.max(0,Math.ceil(energy))+'%',messagesValue:messages+' / 3',scoreValue:score.toLocaleString('ru-RU'),bestValue:Math.max(best(),score).toLocaleString('ru-RU'),speedText:'Шаг настройки: '+step+' МГц'};for(const [id,value] of Object.entries(values))$('#'+id).textContent=value;$('#frequencySlider').value=frequency;$('#signalFill').style.width=signal+'%';$('#beaconField').style.setProperty('--signal',String(signal/100));$('#beaconField').dataset.link=locked&&signal>=84?'transmitting':'searching';$$('.transmissionNodes span').forEach((el,i)=>{el.classList.toggle('done',i<messages);el.setAttribute('aria-label','Сообщение '+(i+1)+(i<messages?' передано':' ожидает'))});$('#signalMeter').setAttribute('aria-valuenow',signal);$('#transferFill').style.width=transfer+'%';$('#transferMeter').setAttribute('aria-valuenow',transfer);$('#lockBtn').textContent=locked?'Снять фиксацию':'Фиксировать';$('#lockBtn').setAttribute('aria-pressed',String(locked));$('#linkBadge').textContent=noise==='active'?'ПОМЕХИ':locked?(signal>=84?'ПЕРЕДАЧА':'СИГНАЛ СЛАБЫЙ'):'ПОИСК';
$$('[data-step]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.step)===step)));for(const id of ['lowerBtn','higherBtn','lockBtn','frequencySlider'])$('#'+id).disabled=phase!=='playing';$$('[data-step]').forEach(b=>b.disabled=phase!=='playing');
const info=noise==='active'?'Помехи! Снимите фиксацию: передача не идёт, запас расходуется быстрее.':noise==='warning'?'Помехи через '+Math.ceil(interferenceState.wait)+' с · снимите фиксацию.':mode==='turbo'?'Помех пока нет · следите за предупреждением.':mode==='b'?'Частота дрейфует · подстраивайте во время передачи.':'Неподвижная частота · фиксация при сигнале от 84%.';$('#interferenceText').textContent=info;$('#interferenceText').classList.toggle('warning',noise!=='clear')}
function setFrequency(n){if(phase!=='playing'||!Number.isFinite(n))return;const before=readSignal();frequency=Math.max(0,Math.min(100,Math.round(n)));const after=readSignal();$('#stateText').textContent=after>before?'Сигнал усилился':after<before?'Сигнал ослаб':'Продолжайте поиск';render();tone('tune')}
function tune(n){setFrequency(frequency+n*step)}
function setStep(n){if(phase!=='playing'||![1,5].includes(n))return;step=n;render()}
function toggleLock(){if(phase!=='playing')return;if(locked){locked=false;$('#stateText').textContent='Фиксация снята · накопленная передача сохранена';render();return}if(interference().kind==='active'){ $('#stateText').textContent='Дождитесь окончания помех';return}if(readSignal()<84){$('#stateText').textContent='Для фиксации нужен сигнал от 84%';return}locked=true;$('#stateText').textContent='Передача идёт · удерживайте сильный сигнал';render();tone('lock')}
function newChannel(){const old=target;do{target=18+Math.floor(Math.random()*65)}while(Math.abs(target-old)<15);direction=Math.random()<.5?-1:1;locked=false;progress=0;$('#stateText').textContent='Новое сообщение · найдите другую частоту'}
function tick(ts){raf=0;if(phase!=='playing')return;const dt=lastTs===null?0:Math.max(0,Math.min(50,ts-lastTs)),seconds=dt/1000;lastTs=ts;clock+=dt;target+=direction*cfg().drift*seconds;if(target>82){target=164-target;direction=-1}else if(target<18){target=36-target;direction=1}const noisy=interference().kind==='active';energy=Math.max(0,energy-seconds*(cfg().drain+(locked&&noisy?12:locked&&readSignal()<84?1.5:0)));
if(energy<=0){finish(false);return}if(locked&&!noisy){if(readSignal()>=84)progress+=seconds;else progress=Math.max(0,progress-seconds*.35);if(progress>=cfg().seconds){messages++;score+=Math.round(100*cfg().mul);tone('sent');if(messages===3){score+=Math.floor(energy);finish(true);return}newChannel()}}render();raf=requestAnimationFrame(tick)}
function start(m=mode){show('game');mode=MODES[m]?m:'a';phase='playing';frequency=50;step=1;energy=100;score=0;messages=0;progress=0;clock=0;saved=false;newChannel();$('#modeBadge').textContent=cfg().label;$('#pauseBtn').textContent='Ⅱ';$('#pauseBtn').setAttribute('aria-label','Пауза');setHero(hero);lastRender='';render(true);raf=requestAnimationFrame(tick)}
function pause(force){if(!['playing','paused'].includes(phase))return;const on=typeof force==='boolean'?force:phase==='playing';cancelAnimationFrame(raf);raf=0;lastTs=null;phase=on?'paused':'playing';document.body.classList.toggle('paused',on);$('#pauseBtn').textContent=on?'▶':'Ⅱ';$('#pauseBtn').setAttribute('aria-label',on?'Продолжить':'Пауза');$('#stateText').textContent=on?'Пауза · нажмите ▶':'Продолжайте настройку';render();if(on)stopAudio();else raf=requestAnimationFrame(tick)}
function save(won){if(saved)return;saved=true;const d=data(),records=d.records&&typeof d.records==='object'?{...d.records}:{},old=Array.isArray(records[mode])?records[mode].filter(r=>r&&finite(r.score)):[];const row={mode,score,messages,energy:Math.floor(energy),won,time:Math.round(clock),date:new Date().toISOString()};records[mode]=[...old,row].sort((a,b)=>b.score-a.score).slice(0,10);window.YouthRecords?.saveGame?.({records,last:row},ID);window.YouthRecords?.updateBest?.(mode,score,ID);if(parent!==window)parent.postMessage({type:'mm-records-changed',game:ID},location.origin)}
function finish(won){if(phase!=='playing')return;phase='result';stop();save(won);$('#resultTitle').textContent=won?'Связь установлена!':'Запас связи исчерпан';$('#resultText').textContent=won?'Все три сообщения переданы. Станция вас услышала!':'Поиск и слабая связь расходуют запас. Найдите сигнал от 84% и попробуйте снова.';$('#resultScore').textContent=score.toLocaleString('ru-RU');$('#resultMessages').textContent=messages+' / 3';$('#resultEnergy').textContent=Math.floor(energy)+'%';render(true);$('#resultOverlay').classList.add('open')}
function records(){const box=$('#recordsList');box.replaceChildren();$$('[data-record-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.recordMode===recordMode)));const arr=data().records?.[recordMode],rows=Array.isArray(arr)?arr.filter(r=>r&&finite(r.score)).slice(0,10):[];if(!rows.length){const p=document.createElement('p');p.textContent='Пока нет результатов в '+MODES[recordMode].label;box.append(p)}for(const [i,r] of rows.entries()){const row=document.createElement('div');row.className='record';for(const text of [i+1,`${Number(r.messages)||0} / 3${r.won?' · Связь установлена':''}`,r.score.toLocaleString('ru-RU')]){const e=document.createElement('span');e.textContent=text;row.append(e)}box.append(row)}}
function tone(kind){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const t=audio.currentTime,g=audio.createGain();g.connect(audio.destination);g.gain.setValueAtTime(.035,t);g.gain.exponentialRampToValueAtTime(.001,t+.25);const notes={tune:[250+readSignal()*3],lock:[540,740],sent:[650,820,1040]}[kind]||[400];notes.forEach((frequency,i)=>{const o=audio.createOscillator();voices.add(o);o.frequency.value=frequency;o.connect(g);o.onended=()=>{voices.delete(o);o.disconnect()};o.start(t+i*.055);o.stop(t+i*.055+.075)});GameLifecycle.schedule(()=>g.disconnect(),500)}catch{}}
$('#startBtn').onclick=()=>show('menu');$$('[data-hero]').forEach(b=>b.onclick=()=>setHero(b.dataset.hero));$$('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('#lowerBtn').onclick=()=>tune(-1);$('#higherBtn').onclick=()=>tune(1);$$('[data-step]').forEach(b=>b.onclick=()=>setStep(Number(b.dataset.step)));$('#frequencySlider').oninput=e=>setFrequency(Number(e.target.value));$('#lockBtn').onclick=toggleLock;$('#pauseBtn').onclick=()=>pause();$('#homeBtn').onclick=()=>show('menu');$('#newBtn').onclick=()=>start();$('#resultMenu').onclick=()=>show('menu');$('#resultReplay').onclick=()=>start();$('#recordsBtn').onclick=()=>{records();$('#recordsOverlay').classList.add('open')};$('#recordsClose').onclick=()=>$('#recordsOverlay').classList.remove('open');$$('[data-record-mode]').forEach(b=>b.onclick=()=>{recordMode=b.dataset.recordMode;records()});$('#screenBtn').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else document.documentElement.requestFullscreen?.().catch(()=>{})};$('#soundBtn').onclick=()=>{soundOn=!soundOn;if(!soundOn)stopAudio();$('#soundBtn').textContent=soundOn?'♪':'×';$('#soundBtn').setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук')};
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||$$('.overlay.open').length)return;if(!['playing','paused'].includes(phase))return;if(e.code==='ArrowLeft'||e.code==='ArrowRight'){e.preventDefault();if(e.shiftKey)setFrequency(frequency+(e.code==='ArrowRight'?5:-5));else tune(e.code==='ArrowRight'?1:-1)}if(e.code==='Enter'){e.preventDefault();if(!e.repeat)toggleLock()}if(e.code==='Space'){e.preventDefault();if(!e.repeat)pause()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&phase==='playing')pause(true)});window.addEventListener('resize',()=>{if(phase==='playing'&&innerWidth>innerHeight&&innerHeight<500)pause(true)});window.addEventListener('pagehide',()=>{stop();phase='closed';audio?.close().catch(()=>{})});
setHero('corgi');show('splash');window.__RADIO_BEACON_QA__=Object.freeze({snapshot:()=>({phase,hero,mode,frequency,signal:readSignal(),step,energy,score,messages,progress,clock,locked,noise:interference().kind,framePending:raf!==0,soundOn,audioState:audio?.state||'none',activeVoices:voices.size})});GameLifecycle.requiredImages=[...Object.values(HERO).map(h=>h.src),"../../assets/retro-props/radio-observatory.webp"];GameLifecycle.engineInitialized=true;
})();
