const fs=require('fs'),path=require('path'),assert=require('assert'),vm=require('vm');
const root=path.resolve(__dirname,'..'),catalog=JSON.parse(fs.readFileSync(root+'/games-manifest.json')); const ids=new Set();
for(const g of catalog.games){
 assert(/^[a-z0-9-]+$/.test(g.id),'Invalid game id');assert(!ids.has(g.id),'Duplicate id');ids.add(g.id);
 for(const key of ['title','desc','cat','entry'])assert(typeof g[key]==='string'&&g[key],`${g.id}: missing ${key}`);
 for(const file of [g.entry,...Object.values(g.assets)]){const resolved=path.resolve(root,file);assert(resolved.startsWith(root+path.sep),'Unsafe path');assert(fs.existsSync(resolved),'Missing '+file)}
}
const ruleContext={window:{}};vm.runInNewContext(fs.readFileSync(root+'/game-rules.js','utf8'),ruleContext);for(const id of ids)assert(ruleContext.window.GalaxyRules.rules[id]?.length===3,'Missing game rules '+id);
const output='// Generated by tools/build-catalog.cjs; edit games-manifest.json.\nwindow.GALAXY_CATALOG='+JSON.stringify(catalog)+';\n';
const context={window:{}};vm.runInNewContext(output,context);assert.equal(context.window.GALAXY_CATALOG.games.length,ids.size,'Generated catalog must execute');
fs.writeFileSync(root+'/catalog.generated.js',output);console.log('Catalog validated and executed:',ids.size);
