(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],ID='energy-capsules';
const MODES={a:{label:'GAME A',spawn:[1180,620],travel:[2750,1900],max:1,guard:520,mul:1},b:{label:'GAME B',spawn:[920,450],travel:[2350,1500],max:2,guard:430,mul:1},turbo:{label:'TURBO',spawn:[720,300],travel:[1950,1050],max:3,guard:300,mul:2}};
const HERO={corgi:{name:'Капитан Корги',src:'../../assets/corgi.png',sheet:'assets/corgi-poses.png'},cat:{name:'Космо-Кот',src:'../../assets/cat.png',sheet:'assets/cat-poses.png'}};
// SVG tracks, receivers and moving objects share this exact normalized geometry.
const LANES=[{sx:6,sy:14,ex:39,ey:47},{sx:94,sy:14,ex:61,ey:47},{sx:6,sy:53,ex:39,ey:70},{sx:94,sy:53,ex:61,ey:70}];
const ANCHORS={corgi:[[.26,.29],[.74,.30],[.25,.61],[.76,.61]],cat:[[.28,.30],[.74,.31],[.26,.75],[.77,.76]]};
const POS=['0% 0%','100% 0%','0% 100%','100% 100%'],NAMES=['Верхняя левая','Верхняя правая','Нижняя левая','Нижняя правая'];
let hero='corgi',mode='a',phase='splash',score=0,lives=3,streak=0,bestStreak=0,caught=0,missed=0,lane=0,objects=[],elapsed=0,lastTs=null,raf=0,seq=0,saved=false,soundOn=true,audio=null,recordMode='a';const voices=new Set();
const validScore=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
function data(){return window.YouthRecords?.getGame?.(ID)||{}}
function best(){const n=window.YouthRecords?.getBest?.(mode,ID);return validScore(n)?n:0}
function config(){return MODES[mode]}
function params(){const t=Math.min(1,caught/70),c=config();return {spawn:c.spawn[0]+(c.spawn[1]-c.spawn[0])*t,travel:c.travel[0]+(c.travel[1]-c.travel[0])*t}}
function stopAudio(){for(const o of voices){try{o.stop()}catch{}}voices.clear();if(audio?.state==='running')audio.suspend().catch(()=>{})}
function stop(){cancelAnimationFrame(raf);raf=0;lastTs=null;for(const o of objects)o.el.remove();objects=[];GameLifecycle.begin();stopAudio();document.body.classList.remove('paused')}
function screen(id){stop();phase=id;$$('.screen').forEach(e=>e.classList.toggle('active',e.id===id));$$('.overlay').forEach(e=>e.classList.remove('open'))}
function setHero(id){hero=HERO[id]?id:'corgi';$$('[data-hero]').forEach(e=>{e.classList.toggle('on',e.dataset.hero===hero);e.setAttribute('aria-pressed',String(e.dataset.hero===hero))});$('#playerImg').src=HERO[hero].src;$('#playerImg').alt=HERO[hero].name;$('#fieldHero').style.backgroundImage=`url("${HERO[hero].sheet}")`;$('#fieldHero').setAttribute('aria-label',HERO[hero].name);pose()}
function clipTracks(){const cut=$('#heroTrackCut'),field=$('#catchField'),el=$('#fieldHero');if(!cut||!field)return;const f=field.getBoundingClientRect(),r=el.getBoundingClientRect();if(!f.width||!f.height)return;for(const [k,v] of Object.entries({x:(r.left-f.left)/f.width*100,y:(r.top-f.top)/f.height*100,width:r.width/f.width*100,height:r.height/f.height*100}))cut.setAttribute(k,v)}
function pose(){const el=$('#fieldHero');el.style.backgroundPosition=POS[lane];el.dataset.lane=lane;el.style.left=LANES[lane].ex+'%';el.style.top=LANES[lane].ey+'%';const [x,y]=ANCHORS[hero][lane];el.style.transform=`translate(${-100*x}%,${-100*y}%)`;$$('.catchBtn,.catchPoint').forEach(e=>{const selected=Number(e.dataset.lane)===lane;e.classList.toggle('on',selected);if(e.matches('button'))e.setAttribute('aria-pressed',String(selected))});clipTracks()}
function choose(n){if(phase!=='playing'||!Number.isInteger(n)||n<0||n>3)return;lane=n;pose();$('#fieldHint').textContent=NAMES[n];tone('move')}
function hud(){const values={scoreValue:score.toLocaleString('ru-RU'),bestValue:Math.max(best(),score).toLocaleString('ru-RU'),livesValue:'●'.repeat(lives)+'○'.repeat(3-lives),streakValue:streak,speedText:'Скорость '+Math.min(9,1+Math.floor(caught/12))};for(const [id,value] of Object.entries(values))$('#'+id).textContent=value;$('#livesValue').setAttribute('aria-label','Жизней: '+lives)}
function scheduleLane(travel){const conflicts=objects.filter(o=>Math.abs((1-o.p)*o.travel-travel)<config().guard);if(!conflicts.length)return Math.floor(Math.random()*4);const n=conflicts[0].lane;return conflicts.every(o=>o.lane===n)?n:null}
function spawn(){if(objects.length>=config().max)return;const bonus=Math.random()<.085,travel=params().travel*(bonus?.88:1),n=scheduleLane(travel);if(n===null)return;const el=document.createElement('div');el.className='capsule'+(bonus?' bonus':'');el.dataset.lane=n;el.dataset.id=++seq;$('#capsuleLayer').append(el);const o={lane:n,travel,p:0,bonus,el};objects.push(o);render(o)}
function render(o){const a=LANES[o.lane],p=Math.min(1,o.p);o.el.style.left=(a.sx+(a.ex-a.sx)*p)+'%';o.el.style.top=(a.sy+(a.ey-a.sy)*p)+'%';o.el.style.setProperty('--angle',Math.atan2(a.ey-a.sy,a.ex-a.sx)*180/Math.PI+'deg')}
function receive(o){objects.splice(objects.indexOf(o),1);o.el.remove();const ok=o.lane===lane;if(ok){const gain=(o.bonus?3:1)*config().mul*Math.min(3,1+Math.floor(streak/10));score+=gain;caught++;streak++;bestStreak=Math.max(bestStreak,streak);$('#stateText').textContent=(o.bonus?'Бонусная капсула':'Капсула принята')+' +'+gain;tone(o.bonus?'bonus':'catch')}else{lives--;missed++;streak=0;$('#stateText').textContent='Пропуск: '+NAMES[o.lane].toLowerCase();tone('miss')}
 const point=$(`.catchPoint[data-lane="${o.lane}"]`);point.classList.remove('caught','missed');point.classList.add(ok?'caught':'missed');GameLifecycle.schedule(()=>point.classList.remove('caught','missed'),250);hud();if(lives===0)finish()}
function tick(ts){raf=0;if(phase!=='playing')return;const dt=lastTs===null?0:Math.max(0,Math.min(50,ts-lastTs));lastTs=ts;elapsed+=dt;if(elapsed>=params().spawn){elapsed=0;spawn()}for(const o of [...objects]){o.p+=dt/o.travel;if(o.p>=1)receive(o);else render(o);if(phase!=='playing')return}raf=requestAnimationFrame(tick)}
function start(m=mode){screen('game');mode=MODES[m]?m:'a';phase='playing';score=0;lives=3;streak=0;bestStreak=0;caught=0;missed=0;lane=0;elapsed=0;saved=false;$('#modeBadge').textContent=config().label;$('#stateText').textContent='Выберите линию до прибытия капсулы';$('#fieldHint').textContent=NAMES[0];$('#pauseBtn').textContent='Ⅱ';$('#pauseBtn').setAttribute('aria-label','Пауза');setHero(hero);hud();raf=requestAnimationFrame(tick)}
function pause(force){if(!['playing','paused'].includes(phase))return;const on=typeof force==='boolean'?force:phase==='playing';cancelAnimationFrame(raf);raf=0;lastTs=null;phase=on?'paused':'playing';document.body.classList.toggle('paused',on);$('#pauseBtn').textContent=on?'▶':'Ⅱ';$('#pauseBtn').setAttribute('aria-label',on?'Продолжить':'Пауза');$('#stateText').textContent=on?'Пауза • нажмите ▶':'Перехватывайте капсулы';if(on)stopAudio();else raf=requestAnimationFrame(tick)}
function save(){if(saved)return;saved=true;const d=data(),records=d.records&&typeof d.records==='object'?{...d.records}:{},old=Array.isArray(records[mode])?records[mode].filter(r=>r&&validScore(r.score)):[];const row={score,caught,missed,bestStreak,mode,date:new Date().toISOString()};records[mode]=[...old,row].sort((a,b)=>b.score-a.score).slice(0,10);window.YouthRecords?.saveGame?.({records,last:row},ID);window.YouthRecords?.updateBest?.(mode,score,ID);if(parent!==window)parent.postMessage({type:'mm-records-changed',game:ID},location.origin)}
function finish(){if(phase!=='playing')return;phase='result';cancelAnimationFrame(raf);raf=0;lastTs=null;save();for(const o of objects)o.el.remove();objects=[];$('#resultTitle').textContent='Раунд завершён';$('#resultText').textContent=`${config().label}: принято ${caught} капсул, пропущено ${missed}. Попробуйте побить свой рекорд!`;$('#resultScore').textContent=score.toLocaleString('ru-RU');$('#resultCaught').textContent=caught;$('#resultCombo').textContent=bestStreak;$('#resultOverlay').classList.add('open');tone('end')}
function records(){const box=$('#recordsList');box.replaceChildren();$$('[data-record-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.recordMode===recordMode)));const arr=data().records?.[recordMode];const rows=Array.isArray(arr)?arr.filter(r=>r&&validScore(r.score)).slice(0,10):[];if(!rows.length){const p=document.createElement('p');p.textContent='Пока нет результатов в '+MODES[recordMode].label;box.append(p)}rows.forEach((r,i)=>{const row=document.createElement('div');row.className='record';for(const text of [i+1,`${Number(r.caught)||0} капсул • серия ${Number(r.bestStreak)||0}`,r.score.toLocaleString('ru-RU')]){const e=document.createElement('span');e.textContent=text;row.append(e)}box.append(row)})}
function tone(kind){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const t=audio.currentTime,g=audio.createGain();g.connect(audio.destination);g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+.26);const frequencies={move:[300],catch:[560,780],bonus:[620,880,1100],miss:[160,125],end:[420,320,240]}[kind];frequencies.forEach((f,i)=>{const o=audio.createOscillator();voices.add(o);o.type=kind==='miss'?'triangle':'sine';o.frequency.value=f;o.connect(g);o.onended=()=>{voices.delete(o);o.disconnect()};o.start(t+i*.055);o.stop(t+i*.055+.07)});GameLifecycle.schedule(()=>g.disconnect(),500)}catch{}}
function geometry(){const svg=$('#laneTracks');svg.innerHTML='<defs><mask id="trackMask" maskUnits="userSpaceOnUse" x="0" y="0" width="100" height="100"><rect width="100" height="100" fill="white"/><rect id="heroTrackCut" rx="9" fill="black"/></mask></defs>';for(const [i,a] of LANES.entries()){const l=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [k,v] of Object.entries({x1:a.sx,y1:a.sy,x2:a.ex,y2:a.ey}))l.setAttribute(k,v);l.setAttribute('mask','url(#trackMask)');svg.append(l);const portal=document.createElementNS('http://www.w3.org/2000/svg','circle');portal.classList.add('lanePortal');portal.setAttribute('cx',a.sx);portal.setAttribute('cy',a.sy);portal.setAttribute('r','3');svg.append(portal);const p=$(`.catchPoint[data-lane="${i}"]`);p.style.left=a.ex+'%';p.style.top=a.ey+'%'}}
$('#startBtn').onclick=()=>screen('menu');$$('[data-hero]').forEach(b=>b.onclick=()=>setHero(b.dataset.hero));$$('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$$('.catchBtn,.laneHit').forEach(b=>b.onclick=()=>choose(Number(b.dataset.lane)));$('#pauseBtn').onclick=()=>pause();$('#homeBtn').onclick=()=>screen('menu');$('#newBtn').onclick=()=>start();$('#screenBtn').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else document.documentElement.requestFullscreen?.().catch(()=>{})};$('#soundBtn').onclick=()=>{soundOn=!soundOn;if(!soundOn)stopAudio();$('#soundBtn').textContent=soundOn?'♪':'×';$('#soundBtn').setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук')};$('#resultMenu').onclick=()=>screen('menu');$('#resultReplay').onclick=()=>start();$('#recordsBtn').onclick=()=>{records();$('#recordsOverlay').classList.add('open')};$('#recordsClose').onclick=()=>$('#recordsOverlay').classList.remove('open');$$('[data-record-mode]').forEach(b=>b.onclick=()=>{recordMode=b.dataset.recordMode;records()});
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||$$('.overlay.open').length){if(e.code==='Escape'&&$('#recordsOverlay').classList.contains('open'))$('#recordsOverlay').classList.remove('open');return}const n={KeyQ:0,KeyE:1,KeyZ:2,KeyC:3,Numpad7:0,Numpad9:1,Numpad1:2,Numpad3:3}[e.code];if(n!==undefined&&['playing','paused'].includes(phase)){e.preventDefault();choose(n)}if(e.code==='Space'&&['playing','paused'].includes(phase)){e.preventDefault();if(!e.repeat)pause()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&phase==='playing')pause(true)});window.addEventListener('resize',()=>{if(phase==='playing'&&innerWidth>innerHeight&&innerHeight<500){pause(true);$('#stateText').textContent='Поворот экрана • нажмите ▶'}});window.addEventListener('pagehide',()=>{stop();phase='closed';audio?.close().catch(()=>{})});
addEventListener('resize',()=>requestAnimationFrame(clipTracks));new ResizeObserver(clipTracks).observe($('#catchField'));geometry();setHero('corgi');screen('splash');window.__ENERGY_CAPSULES_QA__={snapshot:()=>({mode,hero,phase,score,lives,streak,caught,missed,selectedLane:lane,running:phase==='playing'||phase==='paused',paused:phase==='paused',framePending:raf!==0,soundOn,audioState:audio?.state||'none',activeVoices:voices.size,capsules:objects.map(o=>({lane:o.lane,p:o.p,travel:o.travel,bonus:o.bonus}))})};GameLifecycle.requiredImages=Object.values(HERO).flatMap(h=>[h.src,h.sheet]);GameLifecycle.engineInitialized=true;
})();
