// Native browser-only QA. A PASS requires gameplay, layout, navigation and reload.
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=process.env.QA_OUT_DIR||path.join(__dirname,'results');
const base=process.env.QA_BASE_URL?new URL(process.env.QA_BASE_URL).href.replace(/\/?$/, '/'):'http://127.0.0.1:8765/';
assert(/^https?:/.test(base),'QA_BASE_URL must use HTTP(S)');
assert(!new URL(base).search&&!new URL(base).hash,'QA_BASE_URL must be a directory URL without query or fragment');
const games=JSON.parse(fs.readFileSync(root+'/games-manifest.json')).games.filter(g=>!process.env.QA_GAMES||process.env.QA_GAMES.split(',').includes(g.id));
const sizes=[[360,800],[390,844],[430,932]];
const matrix=games.flatMap(g=>sizes.map(([width,height])=>({game:g.id,width,height,status:'NOT_RUN',checks:[],errors:[]})));
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{let p=path.resolve(root,'.'+decodeURI(req.url.split('?')[0]));if(req.url==='/')p=root+'/index.html';try{res.setHeader('Content-Type',mime[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p))}catch(e){res.statusCode=404;res.end('missing')}});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const click=(f,s)=>f.locator(s).first().click({timeout:6000});
async function layout(f,phase){const result=await f.locator('html').evaluate(async (html,phase)=>{
await document.fonts.ready;
const loadedFonts=[...document.fonts].filter(f=>f.status==='loaded').map(f=>f.family.replace(/[\"']/g,''));
const fontErrors=['Montserrat','Unbounded'].filter(name=>!loadedFonts.includes(name)).map(name=>'font not loaded '+name);
const errors=[...fontErrors],active=document.querySelector('.screen.active'),rect=e=>e.getBoundingClientRect(),visible=e=>!!e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden';
if(!active)return ['no active screen'];
if(active.scrollWidth>active.clientWidth+1)errors.push('horizontal overflow in '+phase);
for(const e of active.querySelectorAll('img'))if(visible(e)&&(!e.complete||!e.naturalWidth))errors.push('image not loaded '+e.getAttribute('src'));
const title=active.querySelector('.galaxy-title');if(phase==='game'&&(!title||!visible(title)))errors.push('game title missing');
if(title){if(!getComputedStyle(title).fontFamily.includes('Unbounded'))errors.push('title does not use Unbounded');const r=rect(title);if(r.left<0||r.right>innerWidth+1)errors.push('title clipped');}
if(phase==='menu'){for(const hero of active.querySelectorAll('[data-hero]')){const r=rect(hero);if(r.left<0||r.right>innerWidth+1||r.height<140)errors.push('hero card layout');const img=hero.querySelector('img'),a=img&&rect(img);if(a&&(a.left<r.left||a.right>r.right||a.top<r.top||a.bottom>r.bottom))errors.push('hero image clipped');}}
if(phase==='game'){
const board=active.querySelector('#board,#mainBoard,#bgBoard,#tableau,#chainArea,#catchField,#mailField');if(!board||!visible(board))return [...errors,'playing surface missing'];const r=rect(board);if(r.width<200||r.height<150)errors.push('playing surface collapsed');if(r.left<-.5||r.right>innerWidth+.5)errors.push('board outside viewport');
for(const e of active.querySelectorAll('#topActor,#bottomActor,#leftActor,#rightActor,#actor1,#actor2,.actorMini,#actorImg,#heroImgMini,#playerImg,.controls,.bottomBar')){const a=rect(e);if(visible(e)&&a.width&&a.height&&Math.min(a.right,r.right)>Math.max(a.left,r.left)+1&&Math.min(a.bottom,r.bottom)>Math.max(a.top,r.top)+1)errors.push('overlap '+(e.id||e.className));}
if(document.body.dataset.game==='mahjong')for(const tile of board.querySelectorAll('.tile')){const a=rect(tile);if(a.width<20||a.height<20||a.left<r.left-1||a.right>r.right+1||a.bottom>r.bottom+1)errors.push('mahjong tile hidden/clipped');}
if(document.body.dataset.game==='memory')for(const card of board.querySelectorAll('.memoryCard')){const a=rect(card);if(a.width<40||a.height<40)errors.push('memory touch target too small');}
}
return errors;
},phase);assert.deepEqual(result,[],phase+' layout: '+result.join('; '));}
async function screenshot(p,id,width,phase){await p.screenshot({path:path.join(out,`${id}-${width}-${phase}.png`)});}
async function openGame(p,g){await p.goto(new URL('index.html',base).href);await click(p,'.card[data-play="'+g.id+'"]');await p.locator('#gameLoading').waitFor({state:'hidden',timeout:17000});const f=p.frameLocator('#gameFrame');await f.locator('#splash.active').waitFor();return f;}
async function start(f){await click(f,'#splash.active button');await layout(f,'menu');await click(f,'[data-hero="cat"]');await click(f,'#aiMode,.modeCard');if(await f.locator('.game-modal:visible').count()){assert.equal(await f.locator('.game-modal:visible>.modal-card').count(),1);await click(f,'#startAi,#startSetup,#setupStart');}if(!await f.locator('#game.active').count())await click(f,'#playBtn,#menu .glowBtn');await f.locator('#game.active').waitFor();await sleep(500);}
async function action(id,f,page){const snapshot=()=>f.locator('#board,#mainBoard,#bgBoard,#tableau,#chainTrack,#catchField,#mailField').first().innerHTML();let before=await snapshot();
if(id==='2048'){const b=await f.locator('#board').boundingBox(),cdp=await page.context().newCDPSession(page);for(const [dx,dy]of [[-.25,0],[0,.25],[.25,0]]){const x=b.x+b.width/2,y=b.y+b.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*b.width,y:y+dy*b.height}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}await cdp.detach()}
else if(id==='backgammon'){await click(f,'#rollBtn');await sleep(700);for(let i=0;i<24;i++){await f.locator('.point').nth(i).click();if(await f.locator('.point.legal').count()){await click(f,'.point.legal');break}}}
else if(id==='checkers'){for(let i=0;i<64;i++){const c=f.locator('#board .sq').nth(i);if(await c.locator('.checker.w').count()){await c.click();if(await f.locator('#board .target').count()){await f.locator('#board .sq').filter({has:f.locator('.target')}).first().click();break}}}}
else if(id==='chess'){await click(f,'#board [data-r="6"][data-c="4"]');await click(f,'#board [data-r="4"][data-c="4"]')}
else if(id==='connect4')await click(f,'#boardOverlay button');
else if(id==='corners'){for(let i=0;i<64;i++){const c=f.locator('#board .cell').nth(i);if(await c.locator('.piece.p1').count()){await c.click();if(await f.locator('#board .moveDot').count()){await f.locator('#board .cell').filter({has:f.locator('.moveDot')}).first().click();break}}}}
else if(id==='domino'){await sleep(700);if(await f.locator('#handArea .domino.playable').count())await click(f,'#handArea .domino.playable');else await click(f,'#drawBtn');if(await f.locator('#sideButtons.show').count())await click(f,'#sideButtons button:visible')}
else if(id==='fifteen')await click(f,'#board .tile.movable');
else if(id==='gomoku')await f.locator('#board button').nth(112).click();
else if(id==='mahjong'){const pair=await f.locator('#board .tile.free').evaluateAll(es=>{for(let i=0;i<es.length;i++)for(let j=i+1;j<es.length;j++)if(es[i].querySelector('img').src===es[j].querySelector('img').src)return [es[i].dataset.id,es[j].dataset.id];return []});assert.equal(pair.length,2);for(const n of pair)await click(f,'.tile[data-id="'+n+'"]')}
else if(id==='memory'){const groups=await f.locator('.memoryCard').evaluateAll(es=>{const map={};for(const e of es)(map[e.querySelector('.cardFront').innerHTML]??=[]).push(e.dataset.i);return Object.values(map)});for(const pair of groups){for(const n of pair)await click(f,'.memoryCard[data-i="'+n+'"]');await sleep(450)}await f.locator('#recordName').fill('QA Игрок');await click(f,'#modalActions button');await f.locator('#modalActions button').filter({hasText:'Ещё раз'}).click()}
else if(id==='reversi')await click(f,'#board .cell.valid');
else if(id==='solitaire'){const old=await f.locator('#wasteSlot').innerHTML();await click(f,'#stockSlot .card');assert.notEqual(await f.locator('#wasteSlot').innerHTML(),old);return}
else if(id==='starbattle'){await click(f,'#shuffleBtn');await click(f,'#readyBtn');before=await snapshot();await click(f,'#mainBoard .cell.targetable')}
else if(id==='sudoku'){await click(f,'#board .cell:not(.given)');await click(f,'#notesBtn');await click(f,'#keypad button,[data-num="1"],[data-n="1"]');assert(await f.locator('#board .notes').count());await click(f,'#eraseBtn');assert.equal(await f.locator('#board .notes').count(),0);await click(f,'#notesBtn');await click(f,'#keypad button,[data-num="1"],[data-n="1"]');await click(f,'#checkBoardBtn');await click(f,'#hintBoardBtn')}
else if(id==='tictactoe')await click(f,'#board .cell');
else if(id==='space-mail'){const n=Number(await f.locator('#currentParcel').getAttribute('data-dest'));await click(f,'.routeBtn[data-route="'+n+'"]');await click(f,'#dispatchBtn');assert.equal(await f.locator('#deliveredValue').textContent(),'1 / 15');return}
else if(id==='energy-capsules'){await f.locator('#catchField .capsule').first().waitFor({state:'visible',timeout:5000});const lane=Number(await f.locator('#catchField .capsule').first().getAttribute('data-lane'));await click(f,'.catchBtn[data-lane=\"'+lane+'\"]');await f.locator('#scoreValue').waitFor({state:'visible'});let ok=false;for(let i=0;i<50;i++){const v=Number((await f.locator('#scoreValue').textContent()).replace(/\s/g,''));if(v>0){ok=true;break}await sleep(100)}assert(ok,'Energy capsule was not caught');return}
await sleep(1200);assert.notEqual(await snapshot(),before,'Action did not change board')}

(async()=>{let browser;const catalog=[];fs.mkdirSync(out,{recursive:true});try{
if(!process.env.QA_BASE_URL)await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(8765,'127.0.0.1',resolve);});
browser=await chromium.launch({headless:true,...(process.env.QA_BROWSER_PATH?{executablePath:process.env.QA_BROWSER_PATH}:{}),...(process.env.QA_BROWSER_ARGS?{args:JSON.parse(process.env.QA_BROWSER_ARGS)}:{})});
for(const [width,height] of sizes){const c=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true}),p=await c.newPage(),row={width,height,status:'PASS',checks:[]};try{await p.goto(base);await p.locator('.card').first().waitFor();await p.evaluate(()=>document.fonts.ready);const errors=await p.evaluate(()=>{const e=[],hero=document.querySelector('.portalArt'),r=hero.getBoundingClientRect();if(r.height<400)e.push('hero not enlarged');for(const img of document.querySelectorAll('.gameIconImg')){const a=img.getBoundingClientRect(),b=img.closest('.cardVisual').getBoundingClientRect();if(a.left<b.left||a.right>b.right||a.top<b.top||a.bottom>b.bottom)e.push('catalog image clipped');if(!img.complete||!img.naturalWidth)e.push('catalog image missing');}return e;});assert.deepEqual(errors,[]);assert(await p.locator('.authorCredit').textContent()==='by Alexey Kuznetsov');await screenshot(p,'catalog',width,'hero');await p.locator('.footer').scrollIntoViewIfNeeded();await screenshot(p,'catalog',width,'footer');row.checks.push('hero, safe artwork bounds, credit');}catch(e){row.status='FAIL';row.failure=e.message;}catalog.push(row);await c.close();}
for(const row of matrix){const g=games.find(x=>x.id===row.game),c=await browser.newContext({viewport:{width:row.width,height:row.height},isMobile:true,hasTouch:true}),p=await c.newPage();p.on('pageerror',e=>row.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')row.errors.push(m.text());});p.on('response',r=>{if(r.status()>=400)row.errors.push('HTTP '+r.status()+' '+r.url());});p.on('requestfailed',r=>row.errors.push('request failed '+r.url()));try{
const f=await openGame(p,g);await screenshot(p,g.id,row.width,'splash');await click(f,'#splash.active button');await layout(f,'menu');await screenshot(p,g.id,row.width,'menu');await click(f,'[data-hero="cat"]');await click(f,'#aiMode,.modeCard');if(await f.locator('.game-modal:visible').count()){assert.equal(await f.locator('.game-modal:visible>.modal-card').count(),1);await screenshot(p,g.id,row.width,'settings');await click(f,'#startAi,#startSetup,#setupStart');}if(!await f.locator('#game.active').count())await click(f,'#playBtn,#menu .glowBtn');await f.locator('#game.active').waitFor();await sleep(500);await layout(f,'game');await screenshot(p,g.id,row.width,'game');assert.equal((await f.locator('.galaxy-title').textContent()).trim(),g.title);await action(g.id,f,p);row.checks.push('real gameplay action');
// Native orientation simulation; engine board is unchanged and remains interactable.
await p.setViewportSize({width:row.height,height:row.width});await layout(f,'game');await screenshot(p,g.id,row.width,'landscape');await p.setViewportSize({width:row.width,height:row.height});
await click(f,'#newBtn,#newGameBtn');if(await f.locator('#game.active').count()){await layout(f,'game');await click(f,'#homeBtn,#backMenuBtn')}await f.locator('#menu.active').waitFor();await layout(f,'menu');assert.equal(await f.locator('#allGames').count(),1);await click(f,'#allGames');await p.locator('#gameModal').waitFor({state:'hidden'});assert(await p.locator('.mobileBottomNav').isVisible());
const storageBefore=await p.evaluate(()=>Object.fromEntries(Object.entries(localStorage)));await p.reload();assert.deepEqual(await p.evaluate(()=>Object.fromEntries(Object.entries(localStorage))),storageBefore);row.checks.push('layout, rotation, new, menu, exit, reload storage equality');assert.equal(row.errors.length,0,row.errors.join('; '));row.status='PASS';
}catch(e){row.status='FAIL';row.failure=e.message;await screenshot(p,g.id,row.width,'failure').catch(()=>{});}await c.close();console.log(row.game,row.width,row.status,row.failure||'');fs.writeFileSync(out+'/browser-results-progress.json',JSON.stringify({catalog,matrix},null,2));}
}catch(e){fs.writeFileSync(out+'/browser-launch-error.txt',e.stack||e.message);for(const row of matrix)if(row.status==='NOT_RUN'){row.status='BLOCKED';row.failure='Browser failed before page creation: '+e.message;}process.exitCode=1;
}finally{await browser?.close();if(server.listening)server.close();fs.writeFileSync(out+'/browser-results.json',JSON.stringify({engine:'Playwright Chromium',date:new Date().toISOString(),fullEndStates:false,catalog,matrix},null,2));}})();
