// DOM interaction integration; not a substitute for browser visual/touch QA.
const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const root=path.resolve(__dirname,'..'),checks=[],errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(e.type==='unhandled-exception'||e.type==='resource-loading')errors.push(e.message)});
const server=http.createServer((req,res)=>{try{res.end(fs.readFileSync(path.resolve(root,'.'+decodeURI(req.url.split('?')[0]))))}catch{res.statusCode=404;res.end('missing')}});
(async()=>{await new Promise(r=>server.listen(8767,'127.0.0.1',r));let d;try{
 d=await JSDOM.fromURL('http://127.0.0.1:8767/index.html',{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.matchMedia=()=>({matches:true,addEventListener(){}});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.ResizeObserver=class{observe(){}}}});await new Promise(r=>d.window.addEventListener('load',r));const doc=d.window.document,cards=[...doc.querySelectorAll('.gameLaunch')];assert.equal(cards.length,16);
 for(const card of cards){const id=card.dataset.play;const title=card.querySelector('.catalogTitleArt');assert(title);assert(title.getAttribute('src').endsWith('/'+id+'.png'));assert(fs.existsSync(root+'/'+title.getAttribute('src')));card.querySelector('.gameIconImg').click();await new Promise(r=>setTimeout(r,10));assert(doc.querySelector('#gameModal.open'));assert(doc.querySelector('#gameFrame').getAttribute('src').includes('games/'+id+'/index.html'));doc.querySelector('#closeGame').click();assert(!doc.querySelector('#gameModal.open'));
 for(const key of ['Enter',' ']){card.dispatchEvent(new d.window.KeyboardEvent('keydown',{key,bubbles:true}));await new Promise(r=>setTimeout(r,10));assert(doc.querySelector('#gameModal.open'));assert(doc.querySelector('#gameFrame').getAttribute('src').includes('games/'+id+'/index.html'));d.window.dispatchEvent(new d.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!doc.querySelector('#gameModal.open'));}
 checks.push({game:id,status:'PASS',actions:['icon click','Enter','Space','close / Escape'],title_asset:'present'});
 }
 assert.equal(errors.length,0,errors.join('; '));console.log('16 catalog icons: click, Enter, Space, exit PASS');
}catch(e){console.error(e.message);errors.push(e.message);process.exitCode=1}finally{d?.window.close();server.close();fs.writeFileSync(path.join(__dirname,'results/catalog-art-qa-results.json'),JSON.stringify({runtime:'jsdom, NOT browser visual/touch QA',checks,errors},null,2))}})();
