const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),results=[];const errors=[];
const server=http.createServer((req,res)=>{let p=path.resolve(root,'.'+decodeURI(req.url.split('?')[0]));if(req.url==='/')p=root+'/index.html';try{res.end(fs.readFileSync(p))}catch(e){res.statusCode=404;res.end('missing')}});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{await new Promise(r=>server.listen(8765,'127.0.0.1',r));const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(e.type==='unhandled-exception')errors.push(e.message)});const d=await JSDOM.fromURL('http://127.0.0.1:8765/index.html',{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};w.matchMedia=()=>({matches:true,addListener(){}});w.AudioContext=class{};}});await new Promise(r=>d.window.addEventListener('load',r));const w=d.window,doc=w.document;const test=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',error:e.message})}};
const msg=(data,origin=w.location.origin,source=doc.querySelector('#gameFrame').contentWindow)=>w.dispatchEvent(new w.MessageEvent('message',{origin,source,data}));
await test('Каталог: 16 карточек, поиск и фильтр',()=>{assert.equal(doc.querySelectorAll('#gameGrid .card').length,16);const input=doc.querySelector('#search');input.value='Судоку';input.dispatchEvent(new w.Event('input'));assert.equal(doc.querySelectorAll('#gameGrid .card').length,1);input.value='';input.dispatchEvent(new w.Event('input'));doc.querySelector('[data-cat="logic"]').click();assert.equal(doc.querySelectorAll('#gameGrid .card').length,5);doc.querySelector('[data-cat="all"]').click()});
await test('Готовность принимается только от iframe и текущего launch',async()=>{w.openGame('chess');await delay(400);const epoch=w.eval('loadEpoch');assert.equal(w.eval('loadPhase'),'loading');msg({type:'mm-game-ready',game:'chess',launch:epoch},'https://untrusted.example');assert.equal(w.eval('loadPhase'),'loading');msg({type:'mm-game-ready',game:'chess',launch:epoch-1});assert.equal(w.eval('loadPhase'),'loading');msg({type:'mm-game-ready',game:'chess',launch:epoch});assert.equal(w.eval('loadPhase'),'ready');assert.equal(doc.querySelector('#gameLoading').style.display,'none')});
await test('Fatal error создаёт явную ошибку с retry и каталогом',()=>{msg({type:'mm-game-error',game:'chess',launch:w.eval('loadEpoch'),message:'QA synthetic initialization exception'});assert.equal(w.eval('loadPhase'),'error');assert.equal(doc.querySelectorAll('#gameLoading button').length,2);doc.querySelector('#gameLoading button').click();assert.equal(w.eval('loadPhase'),'loading')});
await test('15 секунд без подтверждения завершаются ошибкой',async()=>{await delay(15400);assert.equal(w.eval('loadPhase'),'error');assert(doc.querySelector('#gameLoading').textContent.includes('15 секунд'));doc.querySelectorAll('#gameLoading button')[1].click();assert(!doc.querySelector('#gameModal.open'));assert(doc.querySelector('#gamesPanel.active'))});
await test('Records: монотонный best и schema v2',()=>{w.YouthRecords.updateBest('4x4',123,'2048');w.YouthRecords.updateBest('4x4',80,'2048');assert.equal(w.YouthRecords.getBest('4x4','2048'),123);const key='youth2048Records',value=JSON.stringify([{score:123,mode:'4x4'}]);w.localStorage.setItem(key,value);assert.equal(w.YouthRecords.getGame('2048').legacy[key],value);assert.equal(w.YouthRecords.exportPayload().schemaVersion,2)});
await test('Scheduler: старые timeout и interval отменяются при новой сессии',async()=>{const q=new JSDOM('',{runScripts:'dangerously'});q.window.eval(fs.readFileSync(root+'/game-lifecycle.js','utf8'));let n=0;const life=q.window.GameLifecycle;life.schedule(()=>n++,20);life.repeat(()=>n++,20);life.begin();await delay(50);assert.equal(n,0);life.schedule(()=>n++,5);await delay(15);assert.equal(n,1);q.window.close()});
await test('Ошибок JS в протокольных тестах нет',()=>assert.equal(errors.length,0,errors.join('; ')));d.window.close();fs.writeFileSync(path.join(__dirname,'results','protocol-qa-results.json'),JSON.stringify({runtime:'jsdom protocol unit tests; readiness and fatal messages are SYNTHETIC',results,errors},null,2));console.log(JSON.stringify(results,null,2));server.close()})()
