const {JSDOM,VirtualConsole}=require('jsdom');const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');const results=[];const requests=[];
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURI(req.url.split('?')[0]));try{const data=fs.readFileSync(p);res.end(data);requests.push({url:req.url,status:200})}catch(e){res.statusCode=404;res.end('not found');requests.push({url:req.url,status:404})}});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function audio(){const param={setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}};const o={connect(){return o},start(){},stop(){},frequency:{...param},gain:{...param}};return {currentTime:0,state:'running',destination:{},createOscillator:()=>o,createGain:()=>o,resume(){}}}
async function load(id){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(e.type==='unhandled-exception'||e.type==='resource-loading')errors.push(e.message)});const d=await JSDOM.fromURL('http://127.0.0.1:8765/games/'+id+'/index.html',{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.matchMedia=()=>({matches:true,addListener(){}});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.ResizeObserver=class{observe(){}};w.AudioContext=audio}});await new Promise(r=>d.window.addEventListener('load',r));return {d,w:d.window,doc:d.window.document,errors}}
function click(doc,selector){const el=doc.querySelector(selector);assert(el,'Missing '+selector);el.click();return el}
function gameSnapshot(doc){return doc.querySelector('#board,#mainBoard,#bgBoard,#tableau,#chainTrack')?.innerHTML}
async function move(id,doc,w){let before;
 if(id==='2048'){before=gameSnapshot(doc);for(const key of ['ArrowLeft','ArrowDown','ArrowRight','ArrowUp'])doc.dispatchEvent(new w.KeyboardEvent('keydown',{key,bubbles:true}));assert.notEqual(gameSnapshot(doc),before);return '4 клавиатурных движения; изменилось поле (свайп не проверен)'}
 if(id==='backgammon'){click(doc,'#rollBtn');await delay(750);let done=false;for(const p of [...doc.querySelectorAll('.point')]){p.click();const target=doc.querySelector('.point.legal');if(target){before=gameSnapshot(doc);target.click();assert.notEqual(gameSnapshot(doc),before);done=true;break}}assert(done,'No legal move after roll');return 'Бросок костей, выбор шашки и допустимое перемещение'}
 if(id==='checkers'){let sq;for(const piece of [...doc.querySelectorAll('#board .checker.w')]){piece.parentElement.click();sq=[...doc.querySelectorAll('#board .sq')].find(e=>e.querySelector('.target'));if(sq)break}before=gameSnapshot(doc);assert(sq,'no move indicator');sq.click();assert.notEqual(gameSnapshot(doc),before);return 'Выбор шашки, допустимый ход; взятие не проверено'}
 if(id==='chess'){before=gameSnapshot(doc);click(doc,'#board [data-r="6"][data-c="4"]');click(doc,'#board [data-r="4"][data-c="4"]');assert.notEqual(gameSnapshot(doc),before);await delay(700);return 'e2–e4 и ответ компьютера'}
 if(id==='connect4'){before=gameSnapshot(doc);click(doc,'#boardOverlay button');await delay(700);assert.notEqual(gameSnapshot(doc),before);return 'Падение фишки и ответ компьютера'}
 if(id==='corners'){let done=false;for(const sq of [...doc.querySelectorAll('#board .cell')]){if(!sq.querySelector('.piece.p1'))continue;sq.click();const target=[...doc.querySelectorAll('#board .cell')].find(e=>e.querySelector('.moveDot'));if(target){before=gameSnapshot(doc);target.click();assert.notEqual(gameSnapshot(doc),before);done=true;break}}assert(done);await delay(1000);return 'Выбор фишки, допустимое перемещение и ответ компьютера'}
 if(id==='domino'){await delay(900);let before=doc.querySelector('#movesBox').textContent;const p=doc.querySelector('#handArea .domino.playable');if(p)p.click();else click(doc,'#drawBtn');for(const sel of ['#leftBtn','#rightBtn']){const e=doc.querySelector(sel);if(e&&e.style.display!=='none'&&doc.querySelector('#sideButtons.show')){e.click();break}}await delay(1000);assert.notEqual(doc.querySelector('#movesBox').textContent,before,'Domino move did not change moves');const ids=[...doc.querySelectorAll('#chainTrack .domino')].map(e=>e.dataset.id);doc.querySelector('#chainArea').dispatchEvent(new w.Event('scroll'));assert.deepEqual([...doc.querySelectorAll('#chainTrack .domino')].map(e=>e.dataset.id),ids);return 'Допустимая кость, ответ ПК; событие scroll сохраняет порядок DOM (геометрия не проверена)'}
 if(id==='fifteen'){before=doc.querySelector('#movesValue').textContent;click(doc,'#board .tile.movable');assert.equal(+doc.querySelector('#movesValue').textContent,+before+1);return 'Передвижение соседней плитки; счётчик увеличился на 1'}
 if(id==='gomoku'){before=gameSnapshot(doc);doc.querySelectorAll('#board button')[112].click();await delay(1000);assert.notEqual(gameSnapshot(doc),before);assert(doc.querySelectorAll('#board .stone').length>=2);return 'Установка камня и ответ компьютера'}
 if(id==='mahjong'){let pair;const free=[...doc.querySelectorAll('#board .tile.free')];for(let i=0;i<free.length;i++)for(let j=i+1;j<free.length;j++)if(free[i].querySelector('img').src===free[j].querySelector('img').src)pair=[free[i].dataset.id,free[j].dataset.id];assert(pair,'no free pair');const n=doc.querySelectorAll('#board .tile').length;for(const id of pair)click(doc,`#board .tile[data-id="${id}"]`);await delay(300);assert.equal(doc.querySelectorAll('#board .tile').length,n-2);return 'Снята реальная доступная пара; число плиток уменьшилось на 2'}
 if(id==='memory'){const cards=[...doc.querySelectorAll('.memoryCard')],groups=new Map();for(const c of cards){const key=c.querySelector('.cardFront').innerHTML;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(c.dataset.i)}for(const indices of groups.values()){assert.equal(indices.length,2);for(const i of indices)click(doc,`.memoryCard[data-i="${i}"]`);await delay(450)}assert.equal(doc.querySelectorAll('.memoryCard.matched').length,cards.length);assert(doc.querySelector('#modal.open'));doc.querySelector('#recordName').value='QA Игрок';click(doc,'#modalActions button');assert(w.localStorage.getItem('youthMemoryRecords'));return `Все ${cards.length/2} пар, завершение партии, запись рекорда через штатное окно`}
 if(id==='reversi'){before=gameSnapshot(doc);const cell=[...doc.querySelectorAll('#board .cell')].find(e=>e.className.includes('valid'));assert(cell,'no legal move');cell.click();await delay(1100);assert.notEqual(gameSnapshot(doc),before);return 'Допустимый ход, переворот и ответ компьютера'}
 if(id==='solitaire'){assert.equal(doc.querySelectorAll('#tableau .card').length,28);before=doc.querySelector('#wasteSlot').innerHTML;click(doc,'#stockSlot .card');assert.notEqual(doc.querySelector('#wasteSlot').innerHTML,before);return 'Раскладка 28 карт; выдача карты из колоды в сброс (foundation/перенос не проверены)'}
 if(id==='starbattle'){click(doc,'#shuffleBtn');click(doc,'#readyBtn');await delay(100);before=gameSnapshot(doc);click(doc,'#mainBoard .cell.targetable');await delay(1000);assert.notEqual(gameSnapshot(doc),before);return 'Перестановка флота, начало боя, выстрел и ответ ПК'}
 if(id==='sudoku'){const index=[...doc.querySelectorAll('#board .cell')].findIndex(e=>!e.classList.contains('given'));doc.querySelectorAll('#board .cell')[index].click();click(doc,'#notesBtn');const key=doc.querySelector('#keypad button,[data-num="1"],[data-n="1"]');assert(key,'no keypad');key.click();assert(doc.querySelectorAll('#board .cell')[index].querySelector('.notes'));click(doc,'#eraseBtn');assert(!doc.querySelectorAll('#board .cell')[index].querySelector('.notes'));click(doc,'#notesBtn');key.click();assert(doc.querySelectorAll('#board .cell')[index].textContent);click(doc,'#checkBoardBtn');click(doc,'#hintBoardBtn');return 'Keypad, заметка, удаление, число, проверка и подсказка'}
 if(id==='tictactoe'){before=gameSnapshot(doc);click(doc,'#board .cell');await delay(1100);assert.notEqual(gameSnapshot(doc),before);assert.equal(doc.querySelectorAll('#board .mark').length,2);return 'Ход X и ответ компьютера O'}
}
const cases=[
 ['2048','big'],['2048','duo'],['backgammon','long'],['tictactoe','5'],['tictactoe','duo'],['connect4','duo'],['gomoku','duo'],['fifteen','timed'],['mahjong','timed'],['memory','timed_4x6'],['memory','classic_6x6'],['solitaire','timed'],['sudoku','timed']
];
(async()=>{await new Promise(r=>server.listen(8765,'127.0.0.1',r));for(const [id,variant]of cases){let env;const r={id,variant,status:'PASS',checks:[]};try{env=await load(id);const {doc,w}=env;click(doc,'#splash button');doc.querySelector('[data-hero="cat"]')?.click();if(id==='backgammon')click(doc,'[data-variant="long"]');
if(variant==='duo'&&['tictactoe','connect4','gomoku'].includes(id))click(doc,'#duoMode');else if(doc.querySelector('#aiMode'))click(doc,'#aiMode');else click(doc,'[data-mode="'+(variant.startsWith('timed')?'timed':variant==='classic_6x6'?'classic':variant)+'"]');
if(id==='tictactoe'&&variant==='5')click(doc,'[data-size="5"]');if(id==='memory')click(doc,'[data-size="'+variant.split('_')[1]+'"]');
const start=doc.querySelector('#startAi,#startSetup,#setupStart');if(start)start.click();if(!doc.querySelector('#game.active'))click(doc,'#playBtn,#menu .glowBtn');assert(doc.querySelector('#game.active'));await delay(1200);
if(id==='tictactoe'&&variant==='duo'){for(const n of [0,3,1,4,2])doc.querySelectorAll('#board .cell')[n].click();assert.equal(doc.querySelectorAll('#board .win').length,3);await delay(450);assert(doc.querySelector('#resultOverlay.open'));r.checks.push('Полная победная линия X на 3×3 в режиме на двоих')}
else if(id==='connect4'&&variant==='duo'){for(const n of [0,1,0,1,0,1,0])doc.querySelectorAll('#boardOverlay button')[n].click();assert.equal(doc.querySelectorAll('#board .disc.win').length,4);r.checks.push('Семь ходов, вертикальная победа из четырёх фишек')}
else if(id==='gomoku'&&variant==='duo'){for(const n of [0,15,1,16,2,17,3,18,4])doc.querySelectorAll('#board button')[n].click();assert.equal(doc.querySelectorAll('#board .stone').length,9);assert.equal(doc.querySelector('#stateLabel').textContent,'Завершено');await delay(250);assert(doc.querySelector('#resultOverlay.open'));r.checks.push('Девять ходов, горизонтальная победа из пяти камней')}
else r.checks.push(await move(id,doc,w));assert(!env.errors.length,env.errors.join('; '));r.errors=env.errors}catch(e){r.status='FAIL';r.failure=e.message;r.errors=env?.errors||[]}finally{env?.w.close()}results.push(r);console.log(id,variant,r.status,r.failure||'')};fs.writeFileSync(path.join(__dirname,'results','variant-qa-results.json'),JSON.stringify({runtime:'jsdom; no native layout or touch',results},null,2));server.close()})();
